---
title: "Take-home - problem set 3"
author: "Clarence Koehle & Yooby Gigandet"
output: pdf_document
---

**1-**

Let $v = (v_t)$ be the relief from the anesthesia and let $c = (c_t)$ be the future costs of the anesthesia on her and the baby's health.

The anesthesia is considered as an immediate rewards and delayed costs. If she chooses to take the anesthesia in period $\tau$, then her intertemporal utility in period $t \le \tau$ is:

$$ 
U_t(\tau) = \begin{cases}  v_\tau - \beta c_\tau\,  & , \space  \space t = \tau \\ 
\beta v_\tau - \beta c_\tau\,  & ,\space  \space t < \tau  \end{cases}
$$
In the model above, we have made the assumption that $\delta = 1$

If she does not choose the anesthesia, then she gets an utility of 0.

**a)**

**i)**

If she is a naive hyperbolic discounter, she mistakenly believes that $\hat\beta = \beta = 1$ when in fact $\beta < \hat\beta = 1$. 

Hence, she will choose to take the anesthesia if 

$$
\hat\beta v_\tau - \hat\beta c_\tau > 0
$$
$$
v_\tau - c_\tau > 0
$$

**ii)**

As she is naive, she assumes that her future self will be time-consistent which is not the case. Hence:

$$
v_\tau - \beta c_\tau > 0
$$

**iii)**

As we have seen above, she will never worry that her tomorrow self might choose an option that she does not like today.

**b)**

**i)**

If she is a sophisticated hyperbolic discounter, she is aware the she is time-inconsistent, hence $\hat\beta = \beta < 1$.

Hence, she will choose to take the anesthesia if 

$$
\beta v_\tau - \beta c_\tau > 0
$$
$$
\beta(v_\tau -c_\tau) > 0
$$

**ii)**

As she is sophisticated, she assumes that her future self will be time-inconsistent. Hence she will take the anesthesia if:

$$
v_\tau - \beta c_\tau > 0
$$

**iii)**

It depends on what she wants. If she doesn't want to take the anesthesia before, and then on the moment, she wants to take the anesthesia. Then she wants to commit to a decision beforehand to avoid the time-inconsistency.

**c)**

**i)**

It is the same as under the point a) i), therefore she will choose to take the anesthesia if:

$$
v_\tau - c_\tau > 0
$$

**ii)**

As she is naive, she assumes that her future self will be time-consistent. Hence, the same condition applies as under the point a) ii):

$$
v_\tau - \beta c_\tau > 0
$$

**iii)**

As she is naive, she will never worry that her tomorrow self might choose an option she does not like today.

**d)**

**i)**

If she is a sophisticated hyperbolic discounter, she is aware the she is time-inconsistent, hence $\hat\beta = \beta < 1$.

Hence, she will choose to take the anesthesia if 

$$
\beta v_\tau - \beta c_\tau > 0
$$
$$
\beta(v_\tau -c_\tau) > 0
$$

**ii)**

As she is sophisticated, she assumes that her future self will be time-inconsistent. Hence she will take the anesthesia if:

$$
v_\tau - \beta c_\tau > 0
$$

**iii)**

It depends on what she wants. If she doesn't want to take the anesthesia before, and then on the moment, she wants to take the anesthesia. Then she wants to commit to a decision beforehand to avoid the time-inconsistency.

**2-**

**a)**

The exponential discounting utility model is given by:

$$
U(c_t, c_{t+1}, c_{t+2}, ...) = \sum_{\tau = 0}^{\infty} \delta^\tau u(c_{t+\tau})
$$
where $0 < \delta < 1$ is a discount factor.

The first inconsistency is given by the fact that families choose a big lump sum in the form of a tax refund the next year instead of smaller installments added to the household head's paycheck each month. 

If we assume that the big lump sum is equal to the sum of the small installments, the discount factor $\delta$ will give more weights to the small installments each month rather than the big lump sum in one year:

$$
\frac{S}{12} + \delta \frac{S}{12} + \delta^2 \frac{S}{12} + ... +\delta^{11} \frac{S}{12} > \delta^{12} S
$$
where $S$ is equal to the lump sum.

Therefore, it makes no sense for the families to choose the big lump sum over the small installments.
Another way would be to check if the discount factor $\delta$ is constant over time, if not we can safely assume that there exists inconsistency. We are going to compare immediate gain, of 2000/12 USD with gains in 4-6-12 months.
$Present\ value = PV = 2000/12$; $Future \space Value = FV = \frac{2000}{3};\frac{2000}{2}; \frac{2000}{1}$;
with $\delta = \frac{PV}{2}$
we have :
$$\delta_4 = (\frac{2000/12}{2000/3})^3 \approx 0.01565 \\; \space \delta_6 = (\frac{2000/12}{2000/2})^2 \approx 0.027 \\; \space \delta_{12} = (\frac{2000/12}{2000})^1 \approx 0.0833  $$
The second inconsistency is given by the fact that most families pay a tax preparer in an effort to get the refund in one day or two instead of filling their taxes themselves an get the refund in a few weeks.

It is inconsistent because for a dynamically consistent decision maker, preferences are constant over time. Thus, in theory individuals should not choose the option of going through H&R Block, as the utility of the tax refund between one day or two and in a few weeks is the same, and because there are an additional costs of using H&R Block, which in turn diminish the utility of the tax refund. In conclusion, an dynamically consistent decision maker will wait and fill her paperwork herself.

**b)**

The hyperbolic utility model is given by:

$$
U_t = u(c_t) + \beta[\delta u(c_{t+1}) + \delta^2 u(c_{t+2})+ ...)]
$$
where:   
$\beta$ uniformly discounts all future periods.   
$\delta$ exponentially discounts all future periods.

For the first fact, because of $0 < \beta < 1$, there is a magnitude effect: small outcomes are discounted more than large outcomes. Thus, families prefer the big lump sum next year rather than the small installments each month.

For the second fact,

Hyperbolic discounting individuals have a dis-utility regarding future gains. This means that they put stronger relative weight on prospect when they get closer. 
preference $(\beta,\delta)$ is defined by:
for all $t, U^t(u_t, u_{t+1},...,u_T$
we have $\delta^{t}u_t+\beta\sum_{\tau = t+1}^{T}\delta^{\tau}u_{\tau}$
with $0 < \beta ,\delta \le1$

**c)**

For time-inconsistent agents it makes sense. As stated before, the attractiveness of direct gains loom larger than future If we now add the idea of credit cards, where the agent will postpone the cost effect of its decision, he can end up in a situation where the amount due at the end of the month exceeds its financial capacity. Thus, the only solution left for this agent is to split the payment due to the credit cards company with high interest rate. Thereby, a time-inconsistent agent in $T+1$ will considers the due payment as a present cost $c+1$, and because he is inconsistent the value of $c+1 > c+2$, he will considers settling his debts directly if the money is readily  available. 

**d)**

For a time-inconsistent agent it makes sense. An agent with hyperbolic discounting will act more impatiently in $t=0$ than in $t=1$.
In this situation, if we consider that the implication of buying a new car which will be consider as a direct gain with future cost (the split payment of the leasing), the only thing that might stop the purchase might be a denied of credit loan by the bank, or simply the factor of current debts needed to be pay as explain in point 1.C. However, the implication of  lump sump payment gain may get rid of the monetary factors. Thus, in a situation where the gain of the lump sump money equate to a new period $t=0$, an agent might act impulsively and buy a new car without consistently thinking about the future due cost. Another point concerning the implication of maintenance cost, those can be considers as future cost. Thereby, with time inconsistency they would be consider lower that the direct cost of starting a leasing $c_o > c_1$, and because $c_o$ will be cover by the lump sump payment received, we can consider that the value is null. 

**3-**

**a)**

Let $u = (u_1, u_2, u_3, u_4) = (3, 5, 8, 13)$ be the utility that she gets from watching each movie for $t = 1, 2, 3, 4$.

Therefore, her discounted utility from the perspective of time $t$ is given by:

$$
U_t = u_t + \beta(u_{t+1} + u_{t+2} + u_{t+3} + ...)
$$

Because Alice is naive, she wrongly believes that she is time-consistent, in other words: $\hat\beta$ = $\beta$ = 1. Therefore, she will plan on watching the last movie because $u_4 > u_3 > u_2 > u_1$. In reality she will chose the third movie because:    

Summary of discounted utilities with $\beta$ = 0.5 and $\delta$ = 1:   

| t         | t = 1 |     t = 2     |     t = 3    |    t = 4     | Ranking |
| :--       | :--   | :--           | :--          | :--          | :--     |
|From self  |       |               |              |              |         |
|t = 1      | 3     | 0.5*5 = 2.5   | 0.5*8 = 4    | 0.5*13 = 6.5 | 4,3,1,2 |
|perspective|       |               |              |              |         |
|           |       |               |              |              |         |
|From self  |       |               |              |              |         |
|t = 2      |       | 5             | 0.5*8 = 4    | 0.5*13 = 6.5 | 4,2,3   |
|perspective|       |               |              |              |         |
|           |       |               |              |              |         |
|From self  |       |               |              |              |         |
|t = 3      |       |               | 8            | 0.5*13 = 6.5 | 3,4     |
|perspective|       |               |              |              |         |

Therefore we can see that:

- At t = 1, she prefers to watch the movie during the week 4, thus she does not go to the first movie:
$2.5 < 3 < 4 < 6.5 = u_2 < u_1 < u_3 < u_4$

- At t = 2, she still prefers to watch the movie during the week 4, thus she does not watch the second film. 
$4 < 5 < 6.5 = u_3 < u_2 < u_4$

- At t = 3, she perceives a higher utility in watching the movie during the week 3 rather than during the week 4.
$6.5 < 8 = u_4 < u_3$

**b)**

Because Alice is sophisticated, she knows that she is time-inconsistent, in other words: $\hat\beta$ = $\beta$ < 1.

Sophisticated people perfectly anticipate the behaviors of their future selves (anticipate they will not stick to the plans) and take this into consideration in their choices over time by using backward induction. Therefore


- At t = 3, she prefers to watch the movie in the third week because:
$6.5 < 8 = u_4 < u_3$

- At t = 2, she knows that she will choose to watch the movie during the week 3 instead of the week 4. Therefore, she compares it with her current view:
$4 < 5 = u_3 < u_2$
Thus, she prefers to watch the movie in the second week.

- At t = 1, with the same principle as above, she compares it with her current view:
$2.5 < 3 = u_2 < u_1$
Thus, she prefers to watch the movie in the first week.

In conclusion, if Alice is sophisticated, she will watch the movie during the first week.

**c)**

Naive Alice gets 3 ticket, therefore:

- At t = 1, she plans to miss the movie on week 2 and therefore watch the movie on week 1:
$2.5 < 3 < 4 < 6.5 = u_2 < u_1 < u_3 < u_4$

- At t = 2, she plans to miss the movie on week 3 and therefore watch the movie on week 2:
$4 < 5 < 6.5 = u_3 < u_2 < u_4$

- At t = 3, she watches the movie on week 3 and therefore miss the one from week 4:
$6.5 < 8 = u_4 < u_3$

**d) **

Sophisticated Alice gets 3 ticket, therefore:


- At t = 2, she prefers to watch the movie on week 2, 3 and 4:
$4 < 5 < 6.5 = u_3 < u_2 < u_4$

- At t = 1, she prefers to switch the second movie by the first one as:
$2.5 < 3 < 4 < 6.5 = u_2 < u_1 < u_3 < u_4$
Thus, she prefers to miss the second movie.

**e)**

If an economist believes that $\beta = 1$, we have the following utility function for Alice:

$$
U_t = u_t + \delta u_{t+1} + \delta^2u_{t+2} + \delta^3u_{t+3} + ...
$$

$$
U_t = \sum_{\tau = 0}^{\infty} \delta^\tau u_{t+\tau}
$$

Summary of utilities with $\beta$ = 1 and $\delta$:   

| t         | t = 1 |     t = 2     |     t = 3    |    t = 4     |
| :--       | :--   | :--           | :--          | :--          |
|From self  |       |               |              |              |
|t = 1      | 3     | $\delta$*5    | $\delta^2$*8 | $\delta^3$*13|
|perspective|       |               |              |              |
|           |       |               |              |              |
|From self  |       |               |              |              |
|t = 2      |       | 5             | $\delta$*8   | $\delta^2$*13|
|perspective|       |               |              |              |
|           |       |               |              |              |
|From self  |       |               |              |              |
|t = 3      |       |               | 8            | $\delta$*13  |
|perspective|       |               |              |              |


Therefore, to find the biggest $\delta$ that an agent with exponential discounting could have such that he would choose the same 3 movies as naive Alice (in other words, movies from the first three weeks)

- At t = 1, if we want Alice to watch the first movie, we must satisfy the following inequation:
$3 > \delta*5$ <=> $\delta < \frac{3}{5}$

- At t = 2, if we want Alice to watch the second movie, we must satisfy they following inequation:
$5 > \delta*8$ <=> $\delta < \frac{5}{8}$

- At t = 3, if we want Alice to watch the third movie, we must satisfy they following inequation:
$8 > \delta*13$ <=> $\delta < \frac{8}{13}$

Hence, $\delta$ < min($\frac{3}{5}$, $\frac{5}{8}$, $\frac{8}{13}$) = $\frac{3}{5}$

**4-**

Let's specify the expected utility of each account:

$$
E(u(w_A)) = w
$$
$$
E(u(w_B)) = w *(1+\frac{0.03}{365}*d)
$$
$$
E(u(w_C)) = (w-e) *(1+\frac{0.05}{365}*d)
$$

where $w$ = $10'000$, $d$ represents the number of days the money spends in the account and $e$ is the cost of switching from account $A$ to $C$, which is equal to 60.

Before going through the exercise, we can easily estimate that $E(u(w_C)) > E(u(w_B)) > E(u(w_A))$. Hence, she should directly place her money in the account C if she was rational and uility maximizer.

**a)**

We first compute the utility of each account from the first day.

Utility of the account A is given by:
$$
u(w_A) = \beta^d w
$$
$$
u(w_A) = 0.9^{10950} * 10'000
$$
$$
u(w_A) = 0
$$

Utility of the account B is given by:
$$
u(w_B) = \beta^d w
$$
$$
u(w_B) = 0.9^{10950}(10'000 *(1+\frac{0.03}{365}*10'950))
$$
$$
u(w_B) = 0
$$

Utility of the account C is given by:
$$
u(w_C) = \beta^d (w-e)
$$
$$
u(w_C) = 0.9^{10950}(9'940 *(1+\frac{0.05}{365}*10'950))
$$
$$
u(w_C) = 0
$$

So, she would keep the money in the account A because $u(w_A) = u(w_B) = u(w_C)$. However, let's see what she thinks she will do tomorrow. As she is naive, she wrongly assumes that $\hat\beta = \beta = 1$ when in fact $\beta < \hat\beta = 1$.

Utility of the account A is given by:

$$
u(w_A) = \hat\beta^d w_A
$$
$$
u(w_A) = 1^{10949} * 10'000
$$
$$
u(w_A) = 10'000
$$

Utility of the account B is given by:

$$
u(w_B) = \hat\beta^d w_B
$$
$$
u(w_B) = 1^{10949}(10'000 *(1+\frac{0.03}{365}*10'949))
$$

$$
u(w_B) = 1^{10949}(10'000 * 1.9)
$$
$$
u(w_B) \approx 18'999
$$

Utility of the account C is given by:

$$
u(w_C) = \hat\beta^d (w_C-e)
$$
$$
u(w_C) = 1^{10949}(9'940 *(1+\frac{0.05}{365}*10'949))
$$
$$
u(w_C) \approx 24'848.6
$$

Hence, she thinks that tomorrow she will switch from the account A to C because $u(w_C) > u(w_B) > u(w_A)$.

**b)**

She will keep doing this until $0.9^d$ is significantly larger than 0. As we can see in the table below, it will be somehow close to the retirement.

| d         | $0.9^d$       |
| :--:      | :--:          |
| 1         | 0.9^1 = 0.9   |
| 2         | 0.9^2 = 0.81  |
| 3         | 0.9^3 = 0.729 |
| ...       | ...           |
| 10        | 0.9^10 = 0.35 |
| ...       | ...           |
| 20        | 0.9^20 = 0.12 |
| ...       | ...           |
| 30        | 0.9^30 = 0.04 |
| ...       | ...           |
| 50        | 0.9^50 = 0.005|
| ...       | ...           |

When this happens, we know that the accounts B and C are more interesting than the account A with no interest rate. In addition, as there is a cost e from switching from account A to C, there will be a time where the account B is more interesting than the account C due to this transaction cost, which diminish the investment amount by $e$, even if the account C has a bigger return on investment (5% > 3%).

**c)**

For her to change her mind, we need to satisfy the following:

$$ 
\begin{cases} 
u(w_B) > u(w_A) \\ 
u(w_B) > u(w_C)  
\end{cases}
$$
$$ 
\begin{cases} 
0.9^d[10'000(1+\frac{0.03}{365}d)] > 0.9^d * 10'000 \\ 
0.9^d[10'000(1+\frac{0.03}{365}d)] > 0.9^d[9'940(1+\frac{0.05}{365}d)]  
\end{cases}
$$
Therefore, as soon as $0.9^d > 0$ the first equation is always satisfied. Therefore, we need to solve the second equation:

$$
0.9^d[10'000(1+\frac{0.03}{365}d)] > 0.9^d[9'940(1+\frac{0.05}{365}d)]
$$
$$
d < 21'900/197 \approx 111.2 
$$
She will transfer the money to the account B when there will be just 111 days remaining before her retirement. Hence, let's check what happens when there is 111 days remaining:

Utility of the account A is given by:
$$
u(w_A) = \beta^d w
$$
$$
u(w_A) = 0.9^{111} * 10'000 - 0
$$
$$
u(w_A) \approx 0.083
$$

Utility of the account B is given by:
$$
u(w_B) = \beta^d w
$$
$$
u(w_B) = 0.9^{111}(10'000 *(1+\frac{0.03}{365}*111))
$$
$$
u(w_B) \approx 0.084
$$

Utility of the account C is given by:
$$
u(w_C) = \beta^d (w_C - e)
$$
$$
u(w_C) = 0.9^{111}(9'940 *(1+\frac{0.05}{365}*111))
$$
$$
u(w_C) \approx 0.084
$$

Hence, she will switch from the account A to the account B when there would be just 111 days remaining before she retires as $u(w_B) > u(w_C) > u(w_A)$

**d)**

If the cost of transfer $e$ was lower, the naive investor will keep her money longer into account A in the hope she will naively switch to account C tomorrow. But as she is time inconsistent, she will never do it. Hence, she will switch to account B even later.

**e)**

If $\delta$ was lower than 1, the naive investor will keep her money even longer than before into account A. And then she will switch to account B even closer to retirement because the $\delta$ will diminish the value of the investment.

**5-**

**a)**

The function maximizing the profit for a firm is:
$$max_p\prod(p) = max_p\delta[(\int_{-\infty}^{\hat{\beta}\delta b-p}(\delta b-a-c)dF(c)-K-\overline{u})+\int_{\beta\delta b-p}^{\hat{\beta}\delta b-p}(\delta b -p-c)dF(c)]$$
Where:
$\int_{-\infty}^{\hat{\beta}\delta b-p}(\delta b-a-c)dF(c)-K-\overline{u})$
corresponds to the social surplus that is generated by the interaction between the agent and the firm at t = 0
the second term:
$\int_{\beta\delta b-p}^{\hat{\beta}\delta b-p}(\delta b -p-c)dF(c)$
is the wrong consumers surplus that is reflect by the principle of overconfidence. This term is defined as follows for a time-inconsistent agent:

$F(\hat{\beta}\delta b -p)-F(\beta\delta b - p) < 0$ 
which corresponds to the overconfidence. This imply that the agent will consume more than what he expected.

The first order condition  for the firm maximization profit is:
$$p^{*} -a = -(1-\hat{\beta})\delta b\frac{f(\hat{\beta}\delta b -p^{*})}{f(\beta\delta b -p^{*})}-\frac{F(\hat{\beta}\delta b -p^{*})-F(\beta\delta b -p^{*})}{f(\beta\delta b -p^{*})}$$
Thus, in the case of a time consistent agent where: $\beta=\hat{\beta < 1}$
the right side of the equation is equal to 0, which imply that $p^{*} = a$
In the case of a time-inconsistent agent where $\beta < \hat{\beta} < 1; b < 0$
then we have that $p^{*} > a$

Concerning the value of $L^{*}$
For a firm this value is defined by:
$$\beta\delta[-L+\int_{-\infty}^{\hat{\beta}\delta b -p}(\delta b -p-c)dF(c)] = \beta\delta\overline{u}$$
This equation implies that the value optimal value of L is dependent to the participation constrain.
Thus a firm aiming at maximizing its profit will put an L < K in order to use at its advantages the principle of overconfidence from a time-inconsistent agent by attracting him with a lower lump sump fee which will in return be compensate by its consumption.


**b)**
The first order condition  for the firm maximization profit is:
$$p^{*} -a = -(1-\hat{\beta})\delta b\frac{f(\hat{\beta}\delta b -p^{*})}{f(\beta\delta b -p^{*})}-\frac{F(\hat{\beta}\delta b -p^{*})-F(\beta\delta b -p^{*})}{f(\beta\delta b -p^{*})}$$
Therefore, looking only at time-inconsistent agent as otherwise with $\beta = \hat{\beta} < 1$ leads to $p^{*} = a$
With $b > 0;\beta < \hat{\beta} < 1$, we get that $p^{*} < a$. To compensate, the firm will therefore have lump sump payment that equate to $L^{*} > K$ because of the following formula:
$$max_{L,p}\delta [L^{*}-K+F(\beta\delta b-p)(p-a)]$$
With 


**c)**
The first order condition  for the firm maximization profit is:
$$p^{*} -a = -(1-\hat{\beta})\delta b\frac{f(\hat{\beta}\delta b -p^{*})}{f(\beta\delta b -p^{*})}-\frac{F(\hat{\beta}\delta b -p^{*})-F(\beta\delta b -p^{*})}{f(\beta\delta b -p^{*})}$$
Therefore, looking only at time-inconsistent agent as otherwise with $\beta = \hat{\beta} < 1$ leads to $p^{*} = a$
With $b < 0;\beta < \hat{\beta} < 1$, we get that $p^{*} > a$

Because we are in a perfect competition format $p_i = p^{*}$ thus the optimal value of $L{*}$ is defined by 
$$\beta\delta[-L^{*}+\int_{-\infty}^{\hat{\beta}\delta b -p}(\delta b -p^{*}-c)dF(c)] = \beta\delta\overline{u}$$
if we substitute $L*$ in the maximization profit function we get:
$$max_p\prod(p^{*}) = max_p\delta[(\int_{-\infty}^{\hat{\beta}\delta b-p^{*}}(\delta b-a-c)dF(c)-K-\overline{u})+\int_{\beta\delta b-p^{*}}^{\hat{\beta}\delta b-p^{*}}(\delta b -p^{*}-c)dF(c)]$$
Because $L^{*}$ is determined by $\overline{u}$ and in equilibrium $\overline{u}$ expected profit is equal to 0, we have that for 
$\beta = \hat{\beta} < 1;b<0$, $L^{*}>K$, because of the following formula:
$$max_{L,p}\delta [L^{*}-K+F(\beta\delta b-p)(p-a)]$$
